name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job de Build
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configura Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Instala dependências
      - name: Install dependencies
        run: |
          npm install

  # Job de Testes (Cypress)
  test:
    runs-on: ubuntu-latest
    needs: build  # Depende do job de build

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configura Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Instala dependências (novamente, para garantir que as dependências sejam instaladas para o Cypress)
      - name: Install dependencies
        run: |
          npm install

      # Executa os testes do Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.config.js
