name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configura Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Instala dependências
      - name: Install dependencies
        run: |
          npm install

      # Inicia o servidor (em segundo plano)
      - name: Start server
        run: |
          nohup node server.js &

      # Executa os testes do Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.config.js
